### ISSUE TITLE
Oxidized Error Handling in Axum

### ISSUE THREAD

**Issue by harshkhandeparkar** [kossiitkgp/top-secret-stuff#27]
Current error handling is done by manually using `match` statements and stringifying error messages. It can be handled using [oxidized ways](https://github.com/tokio-rs/axum/blob/main/examples/anyhow-error-response/src/main.rs). This will enable us to use `?` operator and prevent [`unwrap()` calls](https://github.com/kossiitkgp/top-secret-stuff/blob/bfd42084b4fa1dd9a21fd543e6d488171919c74f/excretor/src/tummy.rs#L19-L20) due to laziness.

**Comment by YoganshSharma** [comment]
_Recommendation:_ Use [color-eyre](https://github.com/eyre-rs/eyre/tree/master/color-eyre) one of [these](https://github.com/eyre-rs/eyre#custom-report-handlers). Eyre is a progression on anyhow. Both are excellent. But one is more beautiful 😍
